In [1]:
from fastchat.model import get_conversation_template


conv = get_conversation_template('/models/Meta-Llama-3-8B-Instruct')
conv

/root/work/EAGLE/env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[2024-08-09 14:46:21,958] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH


/usr/bin/ld: cannot find -laio
collect2: error: ld returned 1 exit status


 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible


Conversation(name='llama-3', system_template='<|start_header_id|>system<|end_header_id|>\n\n{system_message}<|eot_id|>', system_message='', system_message_vision='', roles=('user', 'assistant'), messages=[], offset=0, sep_style=<SeparatorStyle.LLAMA3: 8>, sep='', sep2=None, stop_str='<|eot_id|>', stop_token_ids=[128001, 128009], max_image_size_mb=None)

In [2]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer


tokenizer = AutoTokenizer.from_pretrained('/models/Meta-Llama-3-8B-Instruct', use_fast=False)
model = AutoModelForCausalLM.from_pretrained('/models/Meta-Llama-3-8B-Instruct', device_map="cuda", torch_dtype=torch.float16)
model.eval()

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|██████████| 4/4 [00:05<00:00,  1.43s/it]


LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
  )
  (lm_head): Li

In [5]:
messages = [
	{"role": "system", "content": "You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\\n\\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information."},
	{"role": "user", "content": "Summarize the main ideas of Jeff Walker's Product Launch Formula into bullet points as it pertains to a growth marketing agency implementing these strategies and tactics for their clients..."},
]
messages

[{'role': 'system',
  'content': "You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\\n\\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information."},
 {'role': 'user',
  'content': "Summarize the main ideas of Jeff Walker's Product Launch Formula into bullet points as it pertains to a growth marketing agency implementing these strategies and tactics for their clients..."}]

In [6]:
for msg in messages:
	conv.append_message(msg['role'], msg['content'])

conv.append_message('assistant', '')

prompt = conv.get_prompt()
print(prompt)

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\n\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.<|eot_id|><|start_header_id|>user<|end_header_id|>

Summarize the main ideas of Jeff Walker's Product Launch Formula into bullet points as it pertains to a growth marketing agency implementing these strategies and tactics for their clients...<|eot_id|><|start_header_id|>assistant<|end_header_id|>




In [7]:
input_ids = tokenizer.encode(prompt, return_tensors='pt', add_special_tokens=False).cuda()
input_ids.shape, input_ids

(torch.Size([1, 152]),
 tensor([[128000, 128006,   9125, 128007,    271,   2675,    527,    264,  11190,
              11,  49150,    323,  10978,  18328,     13,  24119,   4320,    439,
            1520,   3725,    439,   3284,     11,   1418,   1694,   6220,     13,
             220,   4718,  11503,   1288,    539,   2997,    904,  28856,     11,
           89735,     11,  25185,     11,  64882,     11,  21503,     11,  11660,
              11,    477,  12079,   2262,     13,   5321,   6106,    430,    701,
           14847,    527,  40418,  74315,    323,   6928,    304,   7138,   7255,
              77,   1734,   2746,    264,   3488,   1587,    539,   1304,    904,
            5647,     11,    477,    374,    539,   2144,   1870,  56887,     11,
           10552,   3249,   4619,    315,  36864,   2555,    539,   4495,     13,
            1442,    499,   1541,    956,   1440,    279,   4320,    311,    264,
            3488,     11,   4587,   1541,    956,   4430,    905,   2038,  

In [6]:
ids2 = torch.as_tensor(tokenizer([prompt], add_special_tokens=False).input_ids)
ids2.shape, ids2

(torch.Size([1, 152]),
 tensor([[128000, 128006,   9125, 128007,    271,   2675,    527,    264,  11190,
              11,  49150,    323,  10978,  18328,     13,  24119,   4320,    439,
            1520,   3725,    439,   3284,     11,   1418,   1694,   6220,     13,
             220,   4718,  11503,   1288,    539,   2997,    904,  28856,     11,
           89735,     11,  25185,     11,  64882,     11,  21503,     11,  11660,
              11,    477,  12079,   2262,     13,   5321,   6106,    430,    701,
           14847,    527,  40418,  74315,    323,   6928,    304,   7138,   7255,
              77,   1734,   2746,    264,   3488,   1587,    539,   1304,    904,
            5647,     11,    477,    374,    539,   2144,   1870,  56887,     11,
           10552,   3249,   4619,    315,  36864,   2555,    539,   4495,     13,
            1442,    499,   1541,    956,   1440,    279,   4320,    311,    264,
            3488,     11,   4587,   1541,    956,   4430,    905,   2038,  

In [7]:
print(tokenizer.decode(input_ids[0].tolist()))

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\n\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.<|eot_id|><|start_header_id|>user<|end_header_id|>

Summarize the main ideas of Jeff Walker's Product Launch Formula into bullet points as it pertains to a growth marketing agency implementing these strategies and tactics for their clients...<|eot_id|><|start_header_id|>assistant<|end_header_id|>




In [8]:
output = model.generate(
    input_ids,
    max_new_tokens=512,
    num_return_sequences=1,
    do_sample=False,
	temperature=0,
)
output.shape, output

/root/work/EAGLE/env/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:389: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/root/work/EAGLE/env/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:394: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


(torch.Size([1, 617]),
 tensor([[128000, 128006,   9125, 128007,    271,   2675,    527,    264,  11190,
              11,  49150,    323,  10978,  18328,     13,  24119,   4320,    439,
            1520,   3725,    439,   3284,     11,   1418,   1694,   6220,     13,
             220,   4718,  11503,   1288,    539,   2997,    904,  28856,     11,
           89735,     11,  25185,     11,  64882,     11,  21503,     11,  11660,
              11,    477,  12079,   2262,     13,   5321,   6106,    430,    701,
           14847,    527,  40418,  74315,    323,   6928,    304,   7138,   7255,
              77,   1734,   2746,    264,   3488,   1587,    539,   1304,    904,
            5647,     11,    477,    374,    539,   2144,   1870,  56887,     11,
           10552,   3249,   4619,    315,  36864,   2555,    539,   4495,     13,
            1442,    499,   1541,    956,   1440,    279,   4320,    311,    264,
            3488,     11,   4587,   1541,    956,   4430,    905,   2038,  

In [8]:
response = tokenizer.decode(output[0], skip_special_tokens=False)
print(response)

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\n\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.<|eot_id|><|start_header_id|>user<|end_header_id|>

Summarize the main ideas of Jeff Walker's Product Launch Formula into bullet points as it pertains to a growth marketing agency implementing these strategies and tactics for their clients...<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Jeff Walker's Product Launch Formula is a comprehensive strategy for launching and marketing products or services. Here's a summar

---

In [2]:
import torch
from eagle.model.ea_model import EaModel


ea_model = EaModel.from_pretrained(
	base_model_path='/models/Meta-Llama-3-8B-Instruct',
	ea_model_path='yuhuili/EAGLE-LLaMA3-Instruct-8B',
	torch_dtype=torch.float16,
	device_map='cuda',
)
ea_model.eval()

Loading checkpoint shards: 100%|██████████| 4/4 [00:05<00:00,  1.43s/it]
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at /models/Meta-Llama-3-8B-Instruct and are newly initialized: ['model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.31.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.23.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.29.self_attn.rotary_emb.inv_freq', 'model.layers.24.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'mode

EaModel(
  (base_model): LlamaForCausalLM(
    (model): LlamaModel(
      (embed_tokens): Embedding(128256, 4096)
      (layers): ModuleList(
        (0-31): 32 x LlamaDecoderLayer(
          (self_attn): LlamaAttention(
            (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (k_proj): Linear(in_features=4096, out_features=1024, bias=False)
            (v_proj): Linear(in_features=4096, out_features=1024, bias=False)
            (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (rotary_emb): LlamaRotaryEmbedding()
          )
          (mlp): LlamaMLP(
            (gate_proj): Linear(in_features=4096, out_features=14336, bias=False)
            (up_proj): Linear(in_features=4096, out_features=14336, bias=False)
            (down_proj): Linear(in_features=14336, out_features=4096, bias=False)
            (act_fn): SiLU()
          )
          (input_layernorm): LlamaRMSNorm()
          (post_attention_layernorm): LlamaRMSNorm

In [3]:
tokenizer = ea_model.tokenizer

In [8]:
output_ids = ea_model.eagenerate(
	input_ids=input_ids,
	#attention_mask=attention_mask,
	is_llama3=True,
	temperature=0,
	max_new_tokens=512,
	top_p=0,
	top_k=0,
)
output_ids

tensor([[128000, 128006,   9125, 128007,    271,   2675,    527,    264,  11190,
             11,  49150,    323,  10978,  18328,     13,  24119,   4320,    439,
           1520,   3725,    439,   3284,     11,   1418,   1694,   6220,     13,
            220,   4718,  11503,   1288,    539,   2997,    904,  28856,     11,
          89735,     11,  25185,     11,  64882,     11,  21503,     11,  11660,
             11,    477,  12079,   2262,     13,   5321,   6106,    430,    701,
          14847,    527,  40418,  74315,    323,   6928,    304,   7138,   7255,
             77,   1734,   2746,    264,   3488,   1587,    539,   1304,    904,
           5647,     11,    477,    374,    539,   2144,   1870,  56887,     11,
          10552,   3249,   4619,    315,  36864,   2555,    539,   4495,     13,
           1442,    499,   1541,    956,   1440,    279,   4320,    311,    264,
           3488,     11,   4587,   1541,    956,   4430,    905,   2038,     13,
         128009, 128006,    

In [9]:
response = tokenizer.decode(output_ids[0], skip_special_tokens=False)
print(response)

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\n\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.<|eot_id|><|start_header_id|>user<|end_header_id|>

Summarize the main ideas of Jeff Walker's Product Launch Formula into bullet points as it pertains to a growth marketing agency implementing these strategies and tactics for their clients...<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Jeff Walker's Product Launch Formula is a comprehensive strategy for launching and marketing products or services. Here's a summar